### ISSUE TITLE
Write Networkstreams to File

### ISSUE THREAD

**Issue by Loris1123** [get-get-get-get/PowerProxy#1]
Hi, thank you for your great proxy!

I would like to be able to analyze the traffic, that is going through the proxy, for example by writing the network streams to a file (pcap?). Do you have any idea or hint how to do that?

**Comment by get-get-get-get** [comment]
Hi, glad you find this project helpful.

It seems possible to copy NetworkStream to file somehow, since we are already copying the stream between connections in Connect-TCPStreams. I'll leave this issue open while I explore the idea.

**Comment by get-get-get-get** [comment]
I think the best way to analyze the traffic is with other tools like _netsh_ or the _NetEventPacketCapture_ module. 

Writing streams to file is viable but formatting it in an analyzable way (e.g. pcap) would be unwieldly because the stream is just application-layer data, and PowerProxy doesn't deal with the actual packets or lower-level TCP details. It's probably doable but the problem is better solved with existing solutions. I'm open to pull requests though.
